-- GameText
-- Author: Evan Norsworthy
-- DateCreated: 10/27/2017 1:34:32 PM
--------------------------------------------------------------
--war-cart
--UPDATE LocalizedText
--SET	Text = 'Sumerian unique Ancient era unit with 28 [ICON_Strength] Melee Strength. No penalties against anti-cavalry units. 4 [ICON_Movement] Movement if this unit starts in open terrain.'
--WHERE Tag = 'LOC_UNIT_SUMERIAN_WAR_CART_DESCRIPTION';
